queue: Hosted VS2017

steps:

- checkout: self
  clean: true

- task: MSBuild@1
  displayName: Restore
  inputs:
    solution: AutoCodeFix.sln
    msbuildArguments: /t:Restore /p:Configuration=Release

- task: MSBuild@1
  displayName: Version
  inputs:
    solution: src/AutoCodeFix.Package/AutoCodeFix.Package.nuproj
    msbuildArguments: /t:SetVersions

- task: MSBuild@1
  displayName: Build
  inputs:
    solution: AutoCodeFix.sln
    msbuildArguments: /bl:"$(Build.ArtifactStagingDirectory)\build.binlog" /p:PackageOutputPath=$(Build.ArtifactStagingDirectory) /p:Configuration=Release

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: out
    ArtifactType: Container
  condition: always()